In [1]:
from junno.j_utils import log
log

<IPython.core.display.Javascript object>

VBox(children=(HBox(children=(HSpace(value='', layout=Layout(width='400px')), LogToolBar(children=(ToolButton(button_color='#bdbdbd', html='<i class="fa fa-info-circle" style="font-size: 20px; color: #2176ff;"></i>', layout=Layout(height='40px', width='40px'), pressed_color='#eee', toggleable=True, value=True), ToolButton(button_color='#bdbdbd', html='<i class="fa fa-exclamation-triangle" style="font-size: 20px; color: #eba427;"></i>', layout=Layout(height='40px', width='40px'), pressed_color='#eee', toggleable=True, value=True), ToolButton(button_color='#bdbdbd', html='<i class="fa fa-exclamation-circle" style="font-size: 20px; color: #c71e1e;"></i>', layout=Layout(height='40px', width='40px'), pressed_color='#eee', toggleable=True, value=True), ToolButton(button_color='#bdbdbd', html='<i class="fa fa-code" style="font-size: 20px; color: #111;"></i>', layout=Layout(height='40px', width='40px'), pressed_color='#eee', toggleable=True, value=True), HTML(value='', layout=Layout(width='25px')), Text(value='', layout=Layout(width='200px'), placeholder='log filters'), HTMLButton(button_color='#bdbdbd', html='Aa', layout=Layout(height='40px', width='40px'), pressed_color='#eee', toggleable=True, value=True)))), layout=Layout(align_items='flex-end', justify_content='space-between')), Accordion(children=(VBox(children=(Accordion(layout=Layout(max_height='500px', width='100%')), VSpace(value='', layout=Layout(height='25px')), LogView(layout=Layout(height='200px', overflow_y='auto'))), layout=Layout(overflow_y='auto')),), _titles={'0': 'global'})))

### Import

In [2]:
import junno.datasets as D
import time
import multiprocessing as mp
import pickle
import numpy as np

In [3]:
def f_wait(x):
    time.sleep(0.1)
    return x

## Image Dataset

In [4]:
PATH = '/home/gaby/Ecole/EPM/MaitriseGit/db/Gabriel/train/'

In [5]:
raw = D.images(PATH+'raw_full/', name='raw')
gt = D.images(PATH+'avgt_full/', name='gt')

In [6]:
join = D.join('name', name=raw.col.name, raw=raw.col.data, gt=gt.col.data)

In [7]:
labelled = join.as_label('gt', {1:'red', 2: 'blue'}, sampling=1/2)
labelled

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

DatabaseView(children=(HBox(children=(ToolBar(children=(ToolButton(html='<i class="fa fa-eye-slash" style="font-size: 20px; color: #333;"></i>', layout=Layout(height='40px', width='40px'), resettable=False, toggleable=True, type='left', value=True), ToolButton(html='<i class="fa fa-list" style="font-size: 20px; color: #333;"></i>', layout=Layout(height='40px', width='40px'), resettable=False, toggleable=True, type='middle'), ToolButton(html='<i class="fa fa-image" style="font-size: 20px; color: #333;"></i>', layout=Layout(height='40px', width='40px'), resettable=False, toggleable=True, type='right'))), HTML(value='', layout=Layout(width='25px')), HierarchyBar(layout=Layout(width='70%'), value=['Join', 'label']), HTML(value='', layout=Layout(width='40px')), RichLabel(value='[88 rows]')), layout=Layout(align_content='flex-end')), VSpace(value='', layout=Layout(height='25px')), SimpleDatabaseView(clear_cache_data=True, columns_name='gt;array(uint32) [1x2048x2048]|name;UNKNOWN|raw;array(float32) [3x2048x2048]', layout=Layout(width='100%'), length=88, visible=False), HBox(children=(BoundedIntText(value=0, description='offset: ', layout=Layout(width='150px'), max=87), BoundedIntText(value=20, description='limit: ', layout=Layout(width='150px'), max=88), HSpace(value='', layout=Layout(width='25px')), TinyLoading(layout=Layout(width='150px'))), layout=Layout(align_items='center', display='none'))))

In [8]:
RD = D.RandomDistribution
da = D.DataAugment().flip_horizontal().rotate()
augmented = labelled.augment(da, N=5)
augmented

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

DatabaseView(children=(HBox(children=(ToolBar(children=(ToolButton(html='<i class="fa fa-eye-slash" style="font-size: 20px; color: #333;"></i>', layout=Layout(height='40px', width='40px'), resettable=False, toggleable=True, type='left', value=True), ToolButton(html='<i class="fa fa-list" style="font-size: 20px; color: #333;"></i>', layout=Layout(height='40px', width='40px'), resettable=False, toggleable=True, type='middle'), ToolButton(html='<i class="fa fa-image" style="font-size: 20px; color: #333;"></i>', layout=Layout(height='40px', width='40px'), resettable=False, toggleable=True, type='right'))), HTML(value='', layout=Layout(width='25px')), HierarchyBar(layout=Layout(width='70%'), value=['Join', 'label', 'augment']), HTML(value='', layout=Layout(width='40px')), RichLabel(value='[440 rows]')), layout=Layout(align_content='flex-end')), VSpace(value='', layout=Layout(height='25px')), SimpleDatabaseView(clear_cache_data=True, columns_name='gt;array(uint32) [1x2048x2048]|name;UNKNOWN|raw;array(float32) [3x2048x2048]', layout=Layout(width='100%'), length=440, visible=False), HBox(children=(BoundedIntText(value=0, description='offset: ', layout=Layout(width='150px'), max=439), BoundedIntText(value=20, description='limit: ', layout=Layout(width='150px'), max=440), HSpace(value='', layout=Layout(width='25px')), TinyLoading(layout=Layout(width='150px'))), layout=Layout(align_items='center', display='none'))))

In [12]:
da(labelled.read(0,2))

[[ 9.98523793e-01 -5.43160563e-02  5.71312772e+01]
 [ 5.43160563e-02  9.98523793e-01 -5.41080061e+01]]
[[ 9.70300833e-01  2.41901411e-01 -2.17295098e+02]
 [-2.41901411e-01  9.70300833e-01  2.78118992e+02]]
[[ 9.98523793e-01 -5.43160563e-02  5.71312772e+01]
 [ 5.43160563e-02  9.98523793e-01 -5.41080061e+01]]
[[ 9.70300833e-01  2.41901411e-01 -2.17295098e+02]
 [-2.41901411e-01  9.70300833e-01  2.78118992e+02]]


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

SimpleDatabaseView(columns_name='pk;TEXT|gt;array(uint32) [1x2048x2048]|name;UNKNOWN|raw;array(float32) [3x2048x2048]', layout=Layout(width='100%'), length=2)

In [ ]:
augmented.get_augmented(labelled.at(0))

In [9]:
stop

NameError: name 'stop' is not defined

## Shuffle

In [ ]:
t = time.time()
d = NumPyDataSet({'id':np.arange(0,50)}).apply('id', f_wait, 'same')
s = d.shuffle(subgen=16)
gen = s.generator(ncore=4, n=4)
for r in gen:
    print(r['id'])
print('%.2fs'%(time.time()-t))

In [ ]:
s.columns.id.format = {'default': '', 0: '0', 1: '1', 2:'2', 3:'3', 4:'4', 5:'5', 6:'test', 7:'7', 8:'8', 9:'9', 10:'10'}

In [ ]:
s

## Standard Datasets

In [ ]:
from junno.datasets import cifar10_datasets
c = cifar10_datasets()['test'].map(x1='x', y='y', x2='x')


In [ ]:
c_dupli = c.apply('x_copy', lambda x1: x1[0], n_factor=None)

In [ ]:
cache = c_dupli.cache(ondisk='test.hd5', overwrite=False)

In [ ]:
cache.select('(y==1) | (y==2) | (y==3)').sort('y')

In [ ]:
cache.mean(ncore=1, end=10)

In [ ]:
cache.std('x_copy', end=2).shape

In [ ]:
cache.std()

## Generator Trace

In [ ]:
gen = out_long.generator(n=7)

In [ ]:
r = gen.next()
r.trace.print()

In [ ]:
out

In [ ]:
c = out_long.as_cache(ncore=4)

In [ ]:
pgen = out_long.generator(parallel_exec=True)

In [ ]:
r.trace.print()

In [ ]:
r = pgen.poll()